add fastboot for android phone

diff --git a/bin/wifi-password b/bin/wifi-password
--- a/bin/wifi-password
+++ b/bin/wifi-password
@@ -87,7 +87,7 @@ pwd=$(echo "$pwd" | sed -e "s/^.*\"\(.*\)\".*$/\1/")
 
 #  https://support.realvnc.com/Knowledgebase/Article/View/518/2/issue-with-keychain-access-on-mac-os-x-10111-el-capitan
 if [ "" == "$pwd" ]; then
-  echo "ERROR: Could not get password. Make sure you don't have any remote/virtual sessions/programs open." >&2
+  echo "ERROR: Could not get password from keychain. Make sure you don't have any remote/virtual sessions/programs open." >&2
   exit 1
 fi
 
