extend our wp-cli update script to get php version from cwd or prompt

diff --git a/bin/wp-upgrade-cwd b/bin/wp-upgrade-cwd
--- a/bin/wp-upgrade-cwd
+++ b/bin/wp-upgrade-cwd
@@ -1,53 +1,74 @@
 #!/usr/bin/env sh
 
+if [ -z ${ACF_PRO_UPDATE_LICENSE+x} ]; then
+  echo "Error: Please configure and export ACF_PRO_UPDATE_LICENSE environment variable."
+  exit 1
+fi
 
-if [ -z ${ACF_PRO_UPDATE_LICENSE+x} ]; then echo "Error: Please configure and export ACF_PRO_UPDATE_LICENSE environment variable.";  exit 1; fi
+# Initialize PHP_VERSION
+PHP_VERSION=""
 
+# Check for .env file in the current directory
+if [ -f .env ]; then
+  # Read PHP_VERSION from .env file
+  PHP_VERSION=$(grep '^PHP_VERSION=' .env | cut -d '=' -f2)
+fi
+
+# If PHP_VERSION is empty, prompt the user
+if [ -z "$PHP_VERSION" ]; then
+  echo "Enter the PHP version your site is running (e.g., 8.0, 8.1, 8.2):"
+  read PHP_VERSION
+fi
+
+# Construct the Docker image tag
+DOCKER_IMAGE="wordpress:cli-php${PHP_VERSION}"
 
 if [ -e wp-config.php ]; then
-  echo "found an install at $pwd"
+  echo "Found an install at $(pwd)"
   rm -rf autoupdate.log
   git checkout master --force
   git pull
   git branch -D update-wp
   git checkout -b update-wp
-  if [ -z ${DOCKER_MACHINE_IP+x} ];
-  then
-    docker run -e ACF_PRO_UPDATE_LICENSE=${ACF_PRO_UPDATE_LICENSE} -v `pwd`:/var/www/html  -i -t wordpress:cli-php8.0   /bin/bash  -c "wp eval 'acf_pro_update_license(\"${ACF_PRO_UPDATE_LICENSE}\");'"
+
+  if [ -z ${DOCKER_MACHINE_IP+x} ]; then
+    docker run -e ACF_PRO_UPDATE_LICENSE=${ACF_PRO_UPDATE_LICENSE} -v "$(pwd)":/var/www/html -i -t ${DOCKER_IMAGE} /bin/bash -c "wp eval 'acf_pro_update_license(\"${ACF_PRO_UPDATE_LICENSE}\");'"
   else
-    docker run -e ACF_PRO_UPDATE_LICENSE=${ACF_PRO_UPDATE_LICENSE} --add-host="host.docker.internal:${DOCKER_MACHINE_IP}" -v `pwd`:/var/www/html  -i -t wordpress:cli-php8.0   /bin/bash  -c "wp eval 'acf_pro_update_license(\"${ACF_PRO_UPDATE_LICENSE}\");'"
+    docker run -e ACF_PRO_UPDATE_LICENSE=${ACF_PRO_UPDATE_LICENSE} --add-host="host.docker.internal:${DOCKER_MACHINE_IP}" -v "$(pwd)":/var/www/html -i -t ${DOCKER_IMAGE} /bin/bash -c "wp eval 'acf_pro_update_license(\"${ACF_PRO_UPDATE_LICENSE}\");'"
   fi
-  echo "\`\`\`" >> autoupdate.log
-  echo "" >> autoupdate.log
-  if [ -z ${DOCKER_MACHINE_IP+x} ];
-  then
-    docker run -v `pwd`:/var/www/html  -i -t wordpress:cli-php8.0   /bin/bash  -c "wp core update" >> autoupdate.log
-  else
-    docker run --add-host="host.docker.internal:${DOCKER_MACHINE_IP}" -v `pwd`:/var/www/html  -i -t wordpress:cli-php8.0   /bin/bash  -c "wp core update" >> autoupdate.log
-  fi
-  echo "\`\`\`" >> autoupdate.log
-  echo "" >> autoupdate.log
-  echo "\`\`\`" >> autoupdate.log
-  echo "" >> autoupdate.log
-  if [ -z ${DOCKER_MACHINE_IP+x} ];
-  then
-    docker run -v `pwd`:/var/www/html  -i -t wordpress:cli-php8.0   /bin/bash  -c "wp plugin update --all" >> autoupdate.log
-  else
-    docker run --add-host="host.docker.internal:${DOCKER_MACHINE_IP}" -v `pwd`:/var/www/html  -i -t wordpress:cli-php8.0   /bin/bash  -c "wp plugin update --all" >> autoupdate.log
-  fi
+
   echo "\`\`\`" >> autoupdate.log
   echo "" >> autoupdate.log
 
-  if [[ -z $(git status -s) ]]
-  then
-    echo "tree is clean"
+  if [ -z ${DOCKER_MACHINE_IP+x} ]; then
+    docker run -v "$(pwd)":/var/www/html -i -t ${DOCKER_IMAGE} /bin/bash -c "wp core update" >> autoupdate.log
+  else
+    docker run --add-host="host.docker.internal:${DOCKER_MACHINE_IP}" -v "$(pwd)":/var/www/html -i -t ${DOCKER_IMAGE} /bin/bash -c "wp core update" >> autoupdate.log
+  fi
+
+  echo "\`\`\`" >> autoupdate.log
+  echo "" >> autoupdate.log
+  echo "\`\`\`" >> autoupdate.log
+  echo "" >> autoupdate.log
+
+  if [ -z ${DOCKER_MACHINE_IP+x} ]; then
+    docker run -v "$(pwd)":/var/www/html -i -t ${DOCKER_IMAGE} /bin/bash -c "wp plugin update --all" >> autoupdate.log
+  else
+    docker run --add-host="host.docker.internal:${DOCKER_MACHINE_IP}" -v "$(pwd)":/var/www/html -i -t ${DOCKER_IMAGE} /bin/bash -c "wp plugin update --all" >> autoupdate.log
+  fi
+
+  echo "\`\`\`" >> autoupdate.log
+  echo "" >> autoupdate.log
+
+  if [[ -z $(git status -s) ]]; then
+    echo "Tree is clean"
   else
     git add -A
     git add -f wp-content/plugins/*/vendor/
     find wp-content/plugins/*/vendor/ -name '.DS_Store' -exec git rm --cached {} \;
-    cat autoupdate.log | sed '/^```/ d' | sed '/^$/d'  | git commit -F -
+    cat autoupdate.log | sed '/^```/ d' | sed '/^$/d' | git commit -F -
     git push -u origin update-wp --verbose
-    gh pr create --title "Automatic Wordpress Updates" --body "$(cat autoupdate.log)"
+    gh pr create --title "Automatic WordPress Updates" --body "$(cat autoupdate.log)"
   fi
 fi
 
